services:
  image_build:
    container_name: image_build
    image: rshcontainer:1
    build: .

  xterm:
    image: rshcontainer:1
    container_name: xterm
    depends_on:
      - image_build
    hostname: xterm
    privileged: true
    command: bash -c "/root/setup.sh && sleep infinity"

  server:
    image: rshcontainer:1
    container_name: server
    depends_on:
      - image_build
    hostname: server
    privileged: true
    command: bash -c "/root/setup.sh && sleep infinity"


  attacker:
    image: rshcontainer:1
    container_name: attacker
    depends_on:
      - image_build
    hostname: attacker
    privileged: true
    command: bash -c "/root/setup.sh && sleep infinity"


networks:
  default:
    name: rede_virtual
